#!/usr/bin/env python3
"""
Add namedCollections to metadata.json processes based on mathematician and theorem mappings.
Run from progframe root. Requires existing metadata.json.
"""
import json
from pathlib import Path

METADATA = Path("/home/gdubs/copernicus-web-public/huggingface-space/mathematics-processes-database/metadata.json")

# (subcat, stem) -> list of collection slugs (mathematicians + theorems)
CHART_TO_COLLECTIONS = {}

def add(proc_id: str, colls: list):
    """proc_id is subcat-stem, e.g. number_theory-sieve-of-eratosthenes"""
    CHART_TO_COLLECTIONS[proc_id] = list(set(CHART_TO_COLLECTIONS.get(proc_id, []) + colls))

# From MATHEMATICIANS
for slug, name, years, blurb, items in [
    ("euclid", "Euclid", "c. 300 BCE", "", [("geometry_topology", "geometry_topology-euclid-elements-i-1-5"),
      ("geometry_topology", "geometry_topology-euclid-elements-book-i-definitions"),
      ("geometry_topology", "geometry_topology-euclid-elements-book-i-props-1-10"),
      ("geometry_topology", "geometry_topology-euclid-elements-book-i-props-11-20"),
      ("geometry_topology", "geometry_topology-euclid-elements-book-i-props-21-30"),
      ("geometry_topology", "geometry_topology-euclid-elements-book-i-props-31-41"),
      ("geometry_topology", "geometry_topology-euclid-elements-book-i-props-42-48"),
      ("geometry_topology", "geometry_topology-euclid-elements-book-ii"),
      ("number_theory", "number_theory-extended-euclidean")]),
    ("archimedes", "Archimedes", "", "", [("geometry_topology", "geometry_topology-euclid-elements-book-xii-props-1-9")]),
    ("eratosthenes", "Eratosthenes", "", "", [("number_theory", "number_theory-sieve-of-eratosthenes")]),
    ("aristotle", "Aristotle", "", "", [("discrete_mathematics", "discrete_mathematics-aristotle-syllogistic-foundations-perfect"),
      ("discrete_mathematics", "discrete_mathematics-aristotle-syllogistic-figure-2"),
      ("discrete_mathematics", "discrete_mathematics-aristotle-syllogistic-figure-3")]),
    ("fermat", "Fermat", "", "", [("number_theory", "number_theory-fermat-last-theorem"),
      ("number_theory", "number_theory-fermat-primality")]),
    ("gauss", "Gauss", "", "", [("statistics_probability", "statistics_probability-central-limit-theorem"),
      ("numerical_analysis", "numerical_analysis-linear-direct"),
      ("numerical_analysis", "numerical_analysis-interpolation")]),
    ("lagrange", "Lagrange", "", "", [("abstract_algebra", "abstract_algebra-group-theory-subgroups-lagrange"),
      ("geometry_topology", "geometry_topology-combinatorics-advanced-counting")]),
    ("laplace", "Laplace", "", "", [("statistics_probability", "statistics_probability-bayes-theorem"),
      ("statistics_probability", "statistics_probability-central-limit-theorem")]),
    ("bayes", "Bayes", "", "", [("statistics_probability", "statistics_probability-bayes-theorem")]),
    ("cauchy", "Cauchy", "", "", [("complex_analysis", "complex_analysis-analytic-cauchy-riemann"),
      ("complex_analysis", "complex_analysis-cauchy-residue"),
      ("calculus_analysis", "calculus_analysis-real-analysis-limits-continuity")]),
    ("riemann", "Riemann", "", "", [("differential_geometry", "differential_geometry-riemannian"),
      ("number_theory", "number_theory-riemann-hypothesis"),
      ("complex_analysis", "complex_analysis-analytic-cauchy-riemann")]),
    ("germain", "Germain", "", "", [("number_theory", "number_theory-fermat-last-theorem"),
      ("number_theory", "number_theory-sieve-of-eratosthenes"),
      ("partial_differential_equations", "partial_differential_equations-classical")]),
    ("kovalevskaya", "Kovalevskaya", "", "", [("partial_differential_equations", "partial_differential_equations-classical"),
      ("partial_differential_equations", "partial_differential_equations-wellposed"),
      ("calculus_analysis", "calculus_analysis-real-analysis-differentiation")]),
    ("galois", "Galois", "", "", [("abstract_algebra", "abstract_algebra-field-theory-galois"),
      ("abstract_algebra", "abstract_algebra-field-theory-extensions"),
      ("abstract_algebra", "abstract_algebra-field-theory-splitting")]),
    ("godel", "Gödel", "", "", [("number_theory", "number_theory-peano-arithmetic-godel-incompleteness-1"),
      ("number_theory", "number_theory-peano-arithmetic-godel-incompleteness-2"),
      ("number_theory", "number_theory-peano-arithmetic-godel-completeness"),
      ("number_theory", "number_theory-peano-arithmetic-godel-formalization"),
      ("number_theory", "number_theory-peano-arithmetic-godel-fol"),
      ("foundations", "foundations-axiomatic-set-theory-ad"),
      ("discrete_mathematics", "discrete_mathematics-model-theory-compactness")]),
    ("peano", "Peano", "", "", [("number_theory", "number_theory-peano-arithmetic-axioms-foundations"),
      ("number_theory", "number_theory-peano-arithmetic-addition-multiplication"),
      ("number_theory", "number_theory-peano-arithmetic-order-induction"),
      ("number_theory", "number_theory-peano-arithmetic-godel-completeness"),
      ("number_theory", "number_theory-peano-arithmetic-godel-incompleteness-1"),
      ("number_theory", "number_theory-peano-arithmetic-godel-incompleteness-2")]),
    ("cartwright", "Cartwright", "", "", [("calculus_analysis", "calculus_analysis-devaney-chaos-definition"),
      ("calculus_analysis", "calculus_analysis-symbolic-dynamics"),
      ("calculus_analysis", "calculus_analysis-complex-dynamics-julia-fatou")]),
    ("noether", "Noether", "", "", [("commutative_algebra", "commutative_algebra-noetherian"),
      ("commutative_algebra", "commutative_algebra-primary-decomp"),
      ("abstract_algebra", "abstract_algebra-ring-theory-ideals-quotients")]),
    ("hilbert", "Hilbert", "", "", [("functional_analysis", "functional_analysis-hilbert-spaces"),
      ("spectral_theory", "spectral_theory-spectrum"),
      ("operator_algebras", "operator_algebras-spectral")]),
    ("kolmogorov", "Kolmogorov", "", "", [("statistics_probability", "statistics_probability-kolmogorov-axioms")]),
    ("vonneumann", "von Neumann", "", "", [("operator_algebras", "operator_algebras-vonneumann"),
      ("operator_algebras", "operator_algebras-gns"),
      ("discrete_mathematics", "discrete_mathematics-merge-sort")]),
    ("dedekind", "Dedekind", "", "", [("abstract_algebra", "abstract_algebra-ring-theory-ideals-quotients"),
      ("number_theory", "number_theory-peano-arithmetic-axioms-foundations")]),
    ("cantor", "Cantor", "", "", [("foundations", "foundations-axiomatic-set-theory-ch-continuum"),
      ("foundations", "foundations-axiomatic-set-theory-ordinals-choice")]),
    ("eilenberg", "Eilenberg", "", "", [("category_theory", "category_theory-category-theory-foundations"),
      ("category_theory", "category_theory-category-theory-natural-transformations")]),
    ("grothendieck", "Grothendieck", "", "", [("algebraic_geometry", "algebraic_geometry-schemes-sheaves"),
      ("algebraic_geometry", "algebraic_geometry-cohomology")]),
    ("serre", "Serre", "", "", [("algebraic_geometry", "algebraic_geometry-cohomology"),
      ("representation_theory", "representation_theory-group-reps")]),
    ("sullivan", "Sullivan", "", "", [("geometry_topology", "geometry_topology-sullivan-minimal-models"),
      ("geometry_topology", "geometry_topology-string-topology"),
      ("calculus_analysis", "calculus_analysis-sullivan-no-wandering-domains"),
      ("calculus_analysis", "calculus_analysis-sullivan-dictionary")]),
    ("wiles", "Wiles", "", "", [("number_theory", "number_theory-fermat-last-theorem")]),
    ("tao", "Tao", "", "", [("number_theory", "number_theory-green-tao-theorem")]),
    ("green", "Green", "", "", [("number_theory", "number_theory-green-tao-theorem")]),
    ("szemeredi", "Szemerédi", "", "", [("number_theory", "number_theory-szemeredi-theorem")]),
    ("dijkstra", "Dijkstra", "", "", [("geometry_topology", "geometry_topology-dijkstra-algorithm")]),
    ("prim", "Prim", "", "", [("geometry_topology", "geometry_topology-prim-algorithm")]),
    ("kruskal", "Kruskal", "", "", [("geometry_topology", "geometry_topology-kruskal-algorithm")]),
    ("hoare", "Hoare", "", "", [("discrete_mathematics", "discrete_mathematics-quicksort")]),
    ("simpson", "Simpson", "", "", [("calculus_analysis", "calculus_analysis-simpsons-rule")]),
    ("shannon", "Shannon", "", "", [("information_theory", "information_theory-entropy"),
      ("information_theory", "information_theory-channel"),
      ("information_theory", "information_theory-coding")]),
    ("rivest", "Rivest", "", "", [("discrete_mathematics", "discrete_mathematics-rsa-algorithm")]),
    ("gelfand", "Gelfand", "", "", [("operator_algebras", "operator_algebras-cstar"),
      ("spectral_theory", "spectral_theory-spectrum")]),
    ("atyiah", "Atiyah", "", "", [("k_theory", "k_theory-topological"), ("operator_algebras", "operator_algebras-spectral")]),
    ("faltings", "Faltings", "", "", [("number_theory", "number_theory-fermat-last-theorem"), ("algebraic_geometry", "algebraic_geometry-schemes-sheaves")]),
    ("deligne", "Deligne", "", "", [("algebraic_geometry", "algebraic_geometry-schemes-sheaves")]),
    ("scholze", "Scholze", "", "", [("algebraic_geometry", "algebraic_geometry-schemes-sheaves"), ("number_theory", "number_theory-fermat-last-theorem")]),
    ("poincare", "Poincaré", "", "", [("geometry_topology", "geometry_topology-homotopy-theory-basics"),
      ("geometry_topology", "geometry_topology-de-rham-cohomology")]),
    ("hamilton", "Hamilton", "", "", [("symplectic_geometry", "symplectic_geometry-hamiltonian"),
      ("mathematical_physics", "mathematical_physics-classical")]),
    ("poisson", "Poisson", "", "", [("symplectic_geometry", "symplectic_geometry-poisson")]),
    ("cartan", "Cartan", "", "", [("differential_geometry", "differential_geometry-forms"),
      ("representation_theory", "representation_theory-lie-algebras")]),
    ("uhlenbeck", "Uhlenbeck", "", "", [("differential_geometry", "differential_geometry-connections"),
      ("differential_geometry", "differential_geometry-riemannian"),
      ("differential_geometry", "differential_geometry-minimal-surfaces"),
      ("partial_differential_equations", "partial_differential_equations-classical")]),
    ("daubechies", "Daubechies", "", "", [("numerical_analysis", "numerical_analysis-interpolation"),
      ("information_theory", "information_theory-entropy"),
      ("functional_analysis", "functional_analysis-hilbert-spaces")]),
    ("mirzakhani", "Mirzakhani", "", "", [("algebraic_geometry", "algebraic_geometry-schemes-sheaves"),
      ("differential_geometry", "differential_geometry-manifolds"),
      ("calculus_analysis", "calculus_analysis-complex-dynamics-julia-fatou")]),
    ("thurston", "Thurston", "", "", [("geometry_topology", "geometry_topology-homotopy-theory-basics"),
      ("geometry_topology", "geometry_topology-de-rham-cohomology"),
      ("geometry_topology", "geometry_topology-point-set-topology-props-1-15"),
      ("geometry_topology", "geometry_topology-algebraic-topology-props-1-15")]),
    ("milnor", "Milnor", "", "", [("calculus_analysis", "calculus_analysis-quadratic-julia-mandelbrot"),
      ("calculus_analysis", "calculus_analysis-complex-dynamics-julia-fatou"),
      ("calculus_analysis", "calculus_analysis-hubbard-douady-collection"),
      ("calculus_analysis", "calculus_analysis-douady-hubbard-mandelbrot-connected"),
      ("differential_geometry", "differential_geometry-manifolds")]),
    ("perelman", "Perelman", "", "", [("geometry_topology", "geometry_topology-homotopy-theory-basics"),
      ("differential_geometry", "differential_geometry-riemannian"),
      ("differential_geometry", "differential_geometry-connections")]),
    ("newton", "Newton", "", "", [("discrete_mathematics", "discrete_mathematics-numerical-methods"),
      ("numerical_analysis", "numerical_analysis-quadrature"),
      ("calculus_analysis", "calculus_analysis-real-analysis-differentiation")]),
    ("julia", "Julia", "", "", [("calculus_analysis", "calculus_analysis-complex-dynamics-julia-fatou"),
      ("calculus_analysis", "calculus_analysis-quadratic-julia-mandelbrot")]),
    ("fatou", "Fatou", "", "", [("calculus_analysis", "calculus_analysis-complex-dynamics-julia-fatou"),
      ("calculus_analysis", "calculus_analysis-quadratic-julia-mandelbrot")]),
    ("douady", "Douady", "", "", [("calculus_analysis", "calculus_analysis-hubbard-douady-collection"),
      ("calculus_analysis", "calculus_analysis-douady-hubbard-mandelbrot-connected"),
      ("calculus_analysis", "calculus_analysis-quadratic-julia-mandelbrot"),
      ("calculus_analysis", "calculus_analysis-boettcher-external-rays"),
      ("calculus_analysis", "calculus_analysis-polynomial-like-maps")]),
    ("hubbard", "Hubbard", "", "", [("calculus_analysis", "calculus_analysis-hubbard-douady-collection"),
      ("calculus_analysis", "calculus_analysis-douady-hubbard-mandelbrot-connected"),
      ("calculus_analysis", "calculus_analysis-quadratic-julia-mandelbrot"),
      ("calculus_analysis", "calculus_analysis-boettcher-external-rays"),
      ("calculus_analysis", "calculus_analysis-polynomial-like-maps")]),
    ("brouwer", "Brouwer", "", "", [("geometry_topology", "geometry_topology-point-set-topology-props-1-15"),
      ("geometry_topology", "geometry_topology-algebraic-topology-props-1-15")]),
    ("ramanujan", "Ramanujan", "", "", [("number_theory", "number_theory-riemann-hypothesis"),
      ("number_theory", "number_theory-chinese-remainder-theorem"),
      ("number_theory", "number_theory-fermat-last-theorem")]),
    ("lebesgue", "Lebesgue", "", "", [("functional_analysis", "functional_analysis-hilbert-spaces"),
      ("functional_analysis", "functional_analysis-banach-spaces"),
      ("calculus_analysis", "calculus_analysis-real-analysis-completeness")]),
    ("weierstrass", "Weierstrass", "", "", [("calculus_analysis", "calculus_analysis-real-analysis-limits-continuity"),
      ("calculus_analysis", "calculus_analysis-real-analysis-completeness"),
      ("numerical_analysis", "numerical_analysis-interpolation")]),
]:
    for sc, st in items:
        add(st, [slug])  # st is full chart id e.g. number_theory-sieve-of-eratosthenes

# Theorem slugs (for theorem-* collections)
for slug, name, stmt, items in [
    ("fermat-last", "", "", [("number_theory", "number_theory-fermat-last-theorem")]),
    ("riemann-hypothesis", "", "", [("number_theory", "number_theory-riemann-hypothesis")]),
    ("chinese-remainder", "", "", [("number_theory", "number_theory-chinese-remainder-theorem")]),
    ("godel-incompleteness", "", "", [("number_theory", "number_theory-peano-arithmetic-godel-incompleteness-1"),
      ("number_theory", "number_theory-peano-arithmetic-godel-incompleteness-2")]),
    ("green-tao", "", "", [("number_theory", "number_theory-green-tao-theorem")]),
    ("szemeredi", "", "", [("number_theory", "number_theory-szemeredi-theorem")]),
    ("bayes", "", "", [("statistics_probability", "statistics_probability-bayes-theorem")]),
    ("central-limit", "", "", [("statistics_probability", "statistics_probability-central-limit-theorem")]),
    ("law-large-numbers", "", "", [("statistics_probability", "statistics_probability-law-of-large-numbers")]),
    ("kolmogorov-axioms", "", "", [("statistics_probability", "statistics_probability-kolmogorov-axioms")]),
    ("lagrange", "", "", [("abstract_algebra", "abstract_algebra-group-theory-subgroups-lagrange")]),
    ("galois-correspondence", "", "", [("abstract_algebra", "abstract_algebra-field-theory-galois")]),
    ("cauchy-riemann", "", "", [("complex_analysis", "complex_analysis-analytic-cauchy-riemann")]),
    ("residue", "", "", [("complex_analysis", "complex_analysis-cauchy-residue")]),
    ("picard", "", "", [("complex_analysis", "complex_analysis-entire-picard")]),
    ("darboux", "", "", [("symplectic_geometry", "symplectic_geometry-darboux")]),
    ("spectral", "", "", [("operator_algebras", "operator_algebras-spectral"),
      ("spectral_theory", "spectral_theory-spectrum"),
      ("spectral_theory", "spectral_theory-selfadjoint")]),
    ("gns", "", "", [("operator_algebras", "operator_algebras-gns")]),
    ("sullivan-wandering", "", "", [("calculus_analysis", "calculus_analysis-sullivan-no-wandering-domains")]),
    ("markov-chains", "", "", [("statistics_probability", "statistics_probability-markov-chains")]),
    ("primality-tests", "", "", [("number_theory", "number_theory-fermat-primality"),
      ("number_theory", "number_theory-miller-rabin"),
      ("number_theory", "number_theory-aks-primality")]),
    ("poincare-conjecture", "", "", [("geometry_topology", "geometry_topology-homotopy-theory-basics"),
      ("geometry_topology", "geometry_topology-de-rham-cohomology")]),
    ("newton-method", "", "", [("discrete_mathematics", "discrete_mathematics-numerical-methods")]),
    ("mandelbrot-connectedness", "", "", [("calculus_analysis", "calculus_analysis-douady-hubbard-mandelbrot-connected"),
      ("calculus_analysis", "calculus_analysis-quadratic-julia-mandelbrot"),
      ("calculus_analysis", "calculus_analysis-hubbard-douady-collection"),
      ("calculus_analysis", "calculus_analysis-boettcher-external-rays")]),
    ("minimal-surfaces", "", "", [("differential_geometry", "differential_geometry-minimal-surfaces"),
      ("differential_geometry", "differential_geometry-riemannian"),
      ("differential_geometry", "differential_geometry-connections")]),
    ("costas-surface", "", "", [("differential_geometry", "differential_geometry-minimal-surfaces")]),
    ("brouwer-fixed-point", "", "", [("geometry_topology", "geometry_topology-point-set-topology-props-1-15"),
      ("geometry_topology", "geometry_topology-algebraic-topology-props-1-15")]),
    ("banach-fixed-point", "", "", [("functional_analysis", "functional_analysis-banach-spaces")]),
    ("stokes", "", "", [("differential_geometry", "differential_geometry-forms")]),
    ("four-color", "", "", [("geometry_topology", "geometry_topology-combinatorics"),
      ("geometry_topology", "geometry_topology-combinatorics-combinations-binomial")]),
    ("jordan-curve", "", "", [("geometry_topology", "geometry_topology-point-set-topology-props-1-15"),
      ("complex_analysis", "complex_analysis-conformal-mappings")]),
    ("fundamental-theorem-algebra", "", "", [("complex_analysis", "complex_analysis-analytic-cauchy-riemann"),
      ("complex_analysis", "complex_analysis-entire-picard")]),
]:
    for sc, st in items:
        add(st, [f"theorem-{slug}"])

def main():
    data = json.loads(METADATA.read_text(encoding="utf-8"))
    updated = 0
    for proc in data.get("processes", []):
        pid = proc.get("id", "")
        if pid in CHART_TO_COLLECTIONS:
            proc["namedCollections"] = sorted(CHART_TO_COLLECTIONS[pid])
            updated += 1
    METADATA.write_text(json.dumps(data, indent=2, ensure_ascii=False), encoding="utf-8")
    print(f"Updated {updated} processes with namedCollections")

if __name__ == "__main__":
    main()
